const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '../src/pages/SectorActivity/signals.ts'), 'utf8');
const target = { exports: {} };
vm.runInNewContext(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, { exports: target.exports });
const { calculateSignals, DEFAULT_SIGNAL_PARAMS: defaults } = target.exports;
const points = (values, ma = 100, quantity = 1) => values.map((amv, i) => ({ date: String(i), amv, ma10: ma, quantity_change: quantity }));
let data = points([100, 107, 108, 99, 98, 106]);
let signals = calculateSignals(data, { ...defaults, exitDrop: 20 });
assert.equal(signals[1].event, 'start');
assert.equal(signals[2].event, null);
assert.equal(signals[3].bull, true);
assert.equal(signals[4].event, 'exit');
assert.equal(signals[5].event, 'start');
assert.equal(calculateSignals(data, defaults)[3].event, 'exit');
assert.equal(calculateSignals(points([100, 105, 110]), defaults)[2].event, 'start');
assert.equal(calculateSignals(points([100, 107], 100, -1), defaults)[1].event, null);
assert.equal(calculateSignals(points([100, 107], null), defaults)[1].event, null);
assert.equal(calculateSignals(points([100, 107], null), { ...defaults, requireMA10: false })[1].event, 'start');
assert.equal(calculateSignals(data, { ...defaults, exitDrop: 20, exitMA10: false })[4].bull, true);
for (let i = 1; i <= data.length; i++) {
  assert.equal(JSON.stringify(calculateSignals(data.slice(0, i), defaults)), JSON.stringify(calculateSignals(data, defaults).slice(0, i)));
}
assert.equal(calculateSignals([], defaults).length, 0);
const history = points([100, 110, 120, 100, 99, 110]).map(point => ({ ...point, price: point.amv }));
const states = calculateSignals(history, defaults);
const returns = target.exports.calculateZoneReturns(history, states);
assert.equal(states[3].event, 'exit');
assert.equal(states[3].zoneBull, true, 'exit day belongs to bull interval');
assert.equal(states[3].bull, false, 'closing state is still bearish');
assert.equal(states[4].zoneBull, false);
assert.equal(returns[3].start, '1');
assert.equal(returns[3].end, '3');
assert.equal(returns[3].total, returns[3].realtime);
assert.equal(returns[4].start, '3', 'bear returns use exit close as base');
const lastExit = target.exports.calculateZoneReturns(history.slice(0, 4), states.slice(0, 4));
assert.equal(lastExit[3].open, false, 'exit on latest day closes bull interval');
const adjacent = points([100, 110, 100, 110]).map(point => ({ ...point, price: point.amv }));
const adjacentReturns = target.exports.calculateZoneReturns(adjacent, calculateSignals(adjacent, defaults));
assert.equal(adjacentReturns[2].end, '2');
assert.equal(adjacentReturns[3].start, '3', 'immediate re-entry starts a new interval');
console.log('PASS: entry filters, compounded two-day entry, exits, re-entry and no future-data dependence');
